spring.application.name: review-service
server.port: 7003
server:
  error:
    include-message: always
logging:
  level:
    root: INFO
    com.sandeep: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/review-db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

spring.datasource.hikari.initializationFailTimeout: 60000

---

spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080

spring.datasource:
  url: jdbc:mysql://mysql/review-db